# Generated by Django 6.0.6 on 2026-06-07 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='Référence')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2, verbose_name='Trimestre')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=12, verbose_name='Statut')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total (FCFA)')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
                ('generee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_generees', to=settings.AUTH_USER_MODEL, verbose_name='Générée par')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-annee', '-trimestre', 'enseignant'],
                'unique_together': {('enseignant', 'trimestre', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('type_seance', models.CharField(max_length=10, verbose_name='Type')),
                ('duree_heures', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Heures')),
                ('tarif_horaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif/h (FCFA)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture', verbose_name='Facture')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='enseignements.seance', verbose_name='Séance')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
            },
        ),
    ]
