# Generated by Django 6.0.6 on 2026-06-07 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom / N°')),
                ('capacite', models.PositiveSmallIntegerField(verbose_name='Capacité')),
                ('type_salle', models.CharField(choices=[('AMPHI', 'Amphithéâtre'), ('SALLE', 'Salle de cours'), ('LABO', 'Laboratoire / Salle TP')], max_length=20, verbose_name='Type')),
                ('batiment', models.CharField(blank=True, max_length=50, verbose_name='Bâtiment')),
                ('equipements', models.TextField(blank=True, verbose_name='Équipements')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code UE')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='Crédits ECTS')),
                ('volume_cours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Volume horaire Cours (h)')),
                ('volume_td', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Volume horaire TD (h)')),
                ('volume_tp', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Volume horaire TP (h)')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Coefficient')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2, verbose_name='Semestre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('poids_cc', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Poids Contrôle Continu (%)')),
                ('poids_exam', models.DecimalField(decimal_places=2, default=60, max_digits=5, verbose_name='Poids Examen Final (%)')),
                ('charge_cours', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ues_cours', to=settings.AUTH_USER_MODEL, verbose_name='Chargé de cours')),
                ('charge_td', models.ForeignKey(blank=True, limit_choices_to={'role': 'ENSEIGNANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ues_td', to=settings.AUTH_USER_MODEL, verbose_name='Chargé de TD/TP')),
                ('classes', models.ManyToManyField(related_name='ues', to='core.classe', verbose_name='Classes concernées')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='core.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': "Unité d'enseignement",
                'verbose_name_plural': "Unités d'enseignement",
                'ordering': ['filiere', 'semestre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seance', models.CharField(choices=[('COURS', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques')], max_length=10, verbose_name='Type de séance')),
                ('date_heure_debut', models.DateTimeField(verbose_name='Début')),
                ('date_heure_fin', models.DateTimeField(verbose_name='Fin')),
                ('duree_heures', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Durée (h)')),
                ('est_validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.classe', verbose_name='Classe')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='enseignements.salle', verbose_name='Salle')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='enseignements.uniteenseignement', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['-date_heure_debut'],
            },
        ),
    ]
