# Generated by Django 6.0.6 on 2026-06-07 14:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('enseignements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: CC1, Partiel, Examen Final', max_length=100, verbose_name='Libellé')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pondération (%)')),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Note maximale')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2, verbose_name='Trimestre')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='enseignements.uniteenseignement', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Évaluation UE',
                'verbose_name_plural': 'Évaluations UE',
                'ordering': ['ue', 'trimestre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], max_length=2, verbose_name='Trimestre')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne générale')),
                ('rang', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rang')),
                ('mention', models.CharField(blank=True, choices=[('INSUFFISANT', 'Insuffisant'), ('PASSABLE', 'Passable'), ('ASSEZ_BIEN', 'Assez Bien'), ('BIEN', 'Bien'), ('TRES_BIEN', 'Très Bien'), ('EXCELLENT', 'Excellent')], max_length=20, verbose_name='Mention')),
                ('appreciations', models.TextField(blank=True, verbose_name='Appréciations')),
                ('publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('date_generation', models.DateTimeField(auto_now=True, verbose_name='Date de génération')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='core.classe', verbose_name='Classe')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-annee', '-trimestre', 'rang'],
                'unique_together': {('etudiant', 'trimestre', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note obtenue')),
                ('absent', models.BooleanField(default=False, verbose_name='Absent / ABS')),
                ('observations', models.CharField(blank=True, max_length=200, verbose_name='Observations')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modif', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.evaluationue', verbose_name='Évaluation')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['evaluation__ue', 'etudiant'],
                'unique_together': {('etudiant', 'evaluation')},
            },
        ),
    ]
