# Generated by Django 6.0.6 on 2026-06-07 14:26

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur'), ('GESTIONNAIRE', 'Gestionnaire / Scolarité'), ('CHEF_FILIERE', 'Chef de Filière'), ('ENSEIGNANT', 'Enseignant'), ('ETUDIANT', 'Étudiant')], default='ETUDIANT', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.photo_profil_path, verbose_name='Photo de profil')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_suspended', models.BooleanField(default=False, verbose_name='Suspendu')),
                ('motif_suspension', models.TextField(blank=True, verbose_name='Motif de suspension')),
                ('otp_secret', models.CharField(blank=True, max_length=64, verbose_name='Secret OTP')),
                ('otp_code', models.CharField(blank=True, max_length=6, verbose_name='Code OTP')),
                ('otp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP créé le')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA activée')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('annee_academique', models.CharField(help_text='Ex: 2025-2026', max_length=9, verbose_name='Année académique')),
                ('chef', models.ForeignKey(blank=True, limit_choices_to={'role': 'CHEF_FILIERE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='Chef de filière')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex: L1 Info A', max_length=50, verbose_name='Libellé')),
                ('niveau', models.CharField(help_text='Ex: L1, L2, M1…', max_length=20, verbose_name='Niveau académique')),
                ('semestre', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2')], max_length=2, verbose_name='Semestre')),
                ('effectif_max', models.PositiveSmallIntegerField(default=50, verbose_name='Effectif maximum')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['filiere', 'libelle'],
                'unique_together': {('filiere', 'libelle', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'action",
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='ProfilEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('DUT', 'DUT / BTS'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('PROFESSEUR', 'Professeur')], max_length=20, verbose_name='Niveau / Grade')),
                ('specialite', models.CharField(blank=True, max_length=150, verbose_name='Spécialité')),
                ('diplome', models.CharField(blank=True, max_length=200, verbose_name='Diplôme le plus élevé')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN / Compte bancaire')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Enseignant',
                'verbose_name_plural': 'Profils Enseignants',
            },
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('redoublant', models.BooleanField(default=False, verbose_name='Redoublant')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='core.classe', verbose_name='Classe')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Étudiant',
                'verbose_name_plural': 'Profils Étudiants',
            },
        ),
        migrations.CreateModel(
            name='TarifNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('DUT', 'DUT / BTS'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('PROFESSEUR', 'Professeur')], max_length=20, unique=True, verbose_name='Niveau')),
                ('tarif_cours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif Cours magistral (FCFA/h)')),
                ('tarif_td', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif TD (FCFA/h)')),
                ('tarif_tp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif TP (FCFA/h)')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifs_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Tarif par niveau',
                'verbose_name_plural': 'Tarifs par niveau',
                'ordering': ['niveau'],
            },
        ),
    ]
